print("A continuación ingresa 10 números para sacar su promedio (solo numeros enteros): ")
n1 = int(input("Numero 1: "))
n2 = int(input("Numero 2: "))
n3 = int(input("Numero 3: "))
n4 = int(input("Numero 4: "))
n5 = int(input("Numero 5: "))
n6 = int(input("Numero 6: "))
n7 = int(input("Numero 7: "))
n8 = int(input("Numero 8: "))
n9 = int(input("Numero 9: "))
n10 = int(input("Numero 10: "))
prom = (n1 + n2 + n3 + n4 + n5 + n6 + n7 + n8 + n9 + n10)/10 
print("El promedio es: ",prom)